In [2]:
import numpy as np
import sys ,time

In [3]:
arr = np.array([23,41,15,65,80])

In [4]:
arr

array([23, 41, 15, 65, 80])

In [5]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
x = x + 5
x

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
y = np.arange(1,11,3)

In [9]:
y

array([ 1,  4,  7, 10])

In [10]:
np.arange(1,15,2,dtype = 'float32')

array([ 1.,  3.,  5.,  7.,  9., 11., 13.], dtype=float32)

In [11]:
np.arange(1,15,2,dtype = 'float8')

TypeError: data type 'float8' not understood

In [9]:
list_1 = [2,3,6,5]
x = np.array([4,5,6,7])

In [10]:
sys.getsizeof([])

56

In [11]:
y = np.array([])

In [12]:
sys.getsizeof(np.array([]))

112

In [13]:
sys.getsizeof([2,3])

72

In [18]:
sys.getsizeof(np.array([2,3]))

120

In [ ]:
sys.getsizeof(np.array([1,2,3,4,6,7,8,9,5,6,2,4]))

In [ ]:
sys.getsizeof([1,2,3,4,6,7,8,9,5,6,2,4])

In [17]:
list_1 = list(range(10000000))
list_2 = list(range(10000000))
lists_3 = []
start = time.time()


for i in range(len(list_1)):
    lists_3.append(list_1[i] + list_2[i])
    
end = time.time()

total = end - start

print("total time taken is:",total)

total time taken is: 3.6577353477478027


In [18]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

start = time.time()

arr_3 = arr_1 + arr_2

end = time.time()
total = end - start
print("total time taken by array is:",total)

total time taken by array is: 0.02473902702331543


In [20]:
np.linspace(2,20,num = 11,retstep = True)

(array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2, 20. ]),
 1.8)

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.random.randn()

-1.876528900289201

In [32]:
np.random.randint(1,10)

9

In [30]:
np.random.randint(1,100,10)

array([10, 46, 74, 66, 57, 94,  4,  6, 61,  6])

In [36]:
x = np.random.randint(1,100,15)

In [34]:
y = np.random.randint(1,100,[4,5])

In [35]:
y

array([[33,  6, 79, 53, 31],
       [54, 62, 77, 97, 44],
       [72, 69, 91,  8, 35],
       [63, 30, 98, 33, 47]])

In [37]:
x

array([90, 82, 98, 61, 62,  9, 30, 40, 70, 37, 29, 18, 99, 24, 34])

In [38]:
x[-1]

34

In [39]:
x[5]

9

In [40]:
x[2:9]

array([98, 61, 62,  9, 30, 40, 70])

In [42]:
y[1:3,0:3]

array([[54, 62, 77],
       [72, 69, 91]])

In [43]:
y[1:5:2,1:5:2]

array([[62, 97],
       [30, 33]])

In [19]:
li = [1,23,4]
li2 = [1,2,3,4]
li + li2

[1, 23, 4, 1, 2, 3, 4]

In [62]:
x = np.random.randint(1,100,15)
x.mean()
np.median(x)

52.0

In [47]:
x.std()

27.578896924198318

In [53]:
y = np.random.randint(1,100,[4,5])
y

array([[ 6, 41,  6, 58, 62],
       [30, 96, 60, 14, 31],
       [17, 51, 68, 92, 56],
       [66,  1, 78, 79,  6]])

In [54]:
y.transpose()

array([[ 6, 30, 17, 66],
       [41, 96, 51,  1],
       [ 6, 60, 68, 78],
       [58, 14, 92, 79],
       [62, 31, 56,  6]])

In [57]:
w = y.ravel()

In [58]:
np.where(w > 30)

(array([ 1,  3,  4,  6,  7,  9, 11, 12, 13, 14, 15, 17, 18], dtype=int64),)

In [59]:
np.any(w > 30)

True

In [60]:
np.all(w > 30)

False